# redirects
[[redirects]]
  from = "http://haukepainter.com/*" 
  to = "http://haukepainters.com/:splat 301!"

[[redirects]]
  from = "http://haukepainter.com/*" 
  to = "http://haukepainters.com/:splat 301!"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


# caching for pictures
[[headers]]
  for = "*.png" 
  [headers.values]
    Cache-Control = "public, max-age=31449600"
[[headers]]
  for = "*.jpg" 
  [headers.values]
    Cache-Control = "public, max-age=31449600"

#caching for fonts
[[headers]]
  for = "*.woff2" 
  [headers.values]
    Cache-Control = "public, max-age=31449600"
[[headers]]
  for = "*.woff" 
  [headers.values]
    Cache-Control = "public, max-age=31449600"
[[headers]]
  for = "*.ttf" 
  [headers.values]
    Cache-Control = "public, max-age=31449600"
[[headers]]
  for = "*.otf" 
  [headers.values]
    Cache-Control = "public, max-age=31449600"